### ISSUE TITLE
how to get Latest clades.tsv

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/nextstrain-walkthrough#4] opened 2024-05-30 12:31 UTC
Hi,

I am new to nextstrain, following your git to build Phylo tree for our lab 2023 data, i have completed all steps until translate, i was wondering how to add clad/lineage data to phylo tree through  

From where can i get clades.csv for the latest lineages to view in add/ export view auspice 
```
augur clades \
  --tree results/tree.nwk \
  --mutations results/nt_muts.json results/aa_muts.json \
  --clades config/clades.tsv \
  --output-node-data results/clades.json
```

**Comment by victorlin** [comment] 2024-05-30 16:55
Closing as duplicate of https://github.com/nextstrain/docs.nextstrain.org/issues/208 which has more information.

**Closed as not planned by victorlin** 2024-05-30 16:55 UTC
Labels: duplicate
